"""deleted end user cred has end user email link

Revision ID: 1ea328d70b85
Revises: 8aff0da1d9e0
Create Date: 2023-06-07 17:00:48.309253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ea328d70b85'
down_revision = '8aff0da1d9e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('endusercredentials', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('end_user', sa.String(), nullable=True))
    #     batch_op.create_foreign_key(batch_op.f('fk_endusercredentials_end_user_endusers'), 'endusers', ['end_user'], ['email'])
	pass

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endusercredentials', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_endusercredentials_end_user_endusers'), type_='foreignkey')
        batch_op.drop_column('end_user')

    # ### end Alembic commands ###
