"""Dropping end user fields to generate fresh migration

Revision ID: 484dd0c2d20f
Revises: 1ea328d70b85
Create Date: 2023-06-07 17:38:21.393321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484dd0c2d20f'
down_revision = '1ea328d70b85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('endusercredentials', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('end_user', sa.Integer(), nullable=True))
    #     batch_op.drop_constraint('fk_endusercredentials_end_user_id_endusers', type_='foreignkey')
    #     batch_op.create_foreign_key(batch_op.f('fk_endusercredentials_end_user_endusers'), 'endusers', ['end_user'], ['id'])
    #     batch_op.drop_column('end_user_id')

    # with op.batch_alter_table('endusers', schema=None) as batch_op:
    #     batch_op.drop_constraint('fk_endusers_parent_org_users', type_='foreignkey')
    #     batch_op.drop_column('origin')
    #     batch_op.drop_column('email')
    #     batch_op.drop_column('parent_org')

    # with op.batch_alter_table('users', schema=None) as batch_op:
    #     batch_op.drop_constraint('unique_api_key', type_='unique')
	pass

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_api_key', ['api_key'])

    with op.batch_alter_table('endusers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_org', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('origin', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_endusers_parent_org_users', 'users', ['parent_org'], ['id'])

    with op.batch_alter_table('endusercredentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_endusercredentials_end_user_endusers'), type_='foreignkey')
        batch_op.create_foreign_key('fk_endusercredentials_end_user_id_endusers', 'endusers', ['end_user_id'], ['id'])
        batch_op.drop_column('end_user')

    # ### end Alembic commands ###
