"""First Revision

Revision ID: 4ac622e4432d
Revises: 
Create Date: 2023-06-06 23:36:12.921417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ac622e4432d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=40), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('pricing_plan', sa.String(length=10), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('api_key', name=op.f('uq_users_api_key')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('uid', name=op.f('uq_users_uid'))
    )
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('credential_id', sa.LargeBinary(), nullable=False),
    sa.Column('credential_public_key', sa.LargeBinary(), nullable=False),
    sa.Column('current_sign_count', sa.Integer(), nullable=True),
    sa.Column('credential_transport', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], name=op.f('fk_credentials_user_email_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credentials'))
    )
    op.create_table('endusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_org', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_org'], ['users.id'], name=op.f('fk_endusers_parent_org_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_endusers'))
    )
    op.create_table('endusercredentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('end_user_id', sa.Integer(), nullable=True),
    sa.Column('credential_id', sa.LargeBinary(), nullable=False),
    sa.Column('credential_public_key', sa.LargeBinary(), nullable=False),
    sa.Column('current_sign_count', sa.Integer(), nullable=True),
    sa.Column('credential_transport', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['end_user_id'], ['endusers.id'], name=op.f('fk_endusercredentials_end_user_id_endusers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_endusercredentials'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('endusercredentials')
    op.drop_table('endusers')
    op.drop_table('credentials')
    op.drop_table('users')
    # ### end Alembic commands ###
