"""Model work

Revision ID: 88c5db0dbc7b
Revises: e9c3e476a657
Create Date: 2023-06-07 01:03:39.323524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88c5db0dbc7b'
down_revision = 'e9c3e476a657'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
