"""deleted end user cred has end user email link

Revision ID: 8aff0da1d9e0
Revises: e2c9dc6455c2
Create Date: 2023-06-07 17:00:33.596697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aff0da1d9e0'
down_revision = 'e2c9dc6455c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('endusercredentials', schema=None) as batch_op:
    #     batch_op.drop_constraint('fk_endusercredentials_end_user_endusers', type_='foreignkey')
    #     batch_op.drop_column('end_user')
	pass

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endusercredentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_user', sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key('fk_endusercredentials_end_user_endusers', 'endusers', ['end_user'], ['email'])

    # ### end Alembic commands ###
