"""Linking end user creds to end user email

Revision ID: 8ec496d732dd
Revises: 8abc5bcc20cb
Create Date: 2023-06-07 16:21:09.398843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec496d732dd'
down_revision = '8abc5bcc20cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('endusercredentials', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('end_user', sa.String(), nullable=True))
    #     #batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(batch_op.f('fk_endusercredentials_end_user_endusers'), 'endusers', ['end_user'], ['email'])
    #     batch_op.drop_column('end_user_id')
	pass

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endusercredentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_endusercredentials_end_user_endusers'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'endusers', ['end_user_id'], ['id'])
        batch_op.drop_column('end_user')

    # ### end Alembic commands ###
