"""Third auto

Revision ID: a67ac1b680ae
Revises: 32116e4632c1
Create Date: 2023-05-13 06:19:28.175594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a67ac1b680ae'
down_revision = '32116e4632c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.LargeBinary(), nullable=False),
    sa.Column('credential_public_key', sa.LargeBinary(), nullable=False),
    sa.Column('current_sign_count', sa.Integer(), nullable=True),
    sa.Column('credential_transport', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('org', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endusercredentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('end_user_id', sa.Integer(), nullable=True),
    sa.Column('credential_id', sa.LargeBinary(), nullable=False),
    sa.Column('credential_public_key', sa.LargeBinary(), nullable=False),
    sa.Column('current_sign_count', sa.Integer(), nullable=True),
    sa.Column('credential_transport', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['end_user_id'], ['endusers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('endusercredentials')
    op.drop_table('endusers')
    op.drop_table('credentials')
    op.drop_table('users')
    # ### end Alembic commands ###
