"""capture new columns

Revision ID: b0325653e017
Revises: 99a417ac03ee
Create Date: 2023-06-05 17:40:44.212727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0325653e017'
down_revision = '99a417ac03ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
	op.create_table('users',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('uid', sa.String(length=40), nullable=True),
	sa.Column('email', sa.String(length=150), nullable=True),
	sa.Column('pricing_plan', sa.String(length=10), nullable=True),
	sa.Column('login_count', sa.Integer(), nullable=True),
	sa.PrimaryKeyConstraint('id'),
	sa.UniqueConstraint('email'),
	sa.UniqueConstraint('uid')
	)
	op.create_table('credentials',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('user_email', sa.Integer(), nullable=False),
	sa.Column('credential_id', sa.LargeBinary(), nullable=False),
	sa.Column('credential_public_key', sa.LargeBinary(), nullable=False),
	sa.Column('current_sign_count', sa.Integer(), nullable=True),
	sa.Column('credential_transport', sa.String(), nullable=True),
	sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
	sa.PrimaryKeyConstraint('id')
	)
	op.create_table('endusers',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('email', sa.String(), nullable=True),
	sa.Column('org', sa.Integer(), nullable=True),
	sa.ForeignKeyConstraint(['org'], ['users.id'], ),
	sa.PrimaryKeyConstraint('id')
	)
	op.create_table('endusercredentials',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('end_user_id', sa.Integer(), nullable=True),
	sa.Column('credential_id', sa.LargeBinary(), nullable=False),
	sa.Column('credential_public_key', sa.LargeBinary(), nullable=False),
	sa.Column('current_sign_count', sa.Integer(), nullable=True),
	sa.Column('credential_transport', sa.String(), nullable=True),
	sa.ForeignKeyConstraint(['end_user_id'], ['endusers.id'], ),
	sa.PrimaryKeyConstraint('id')
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table('users',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('uid', sa.String(length=40), nullable=True),
	sa.Column('email', sa.String(length=150), nullable=True),
	sa.PrimaryKeyConstraint('id'),
	sa.UniqueConstraint('email'),
	sa.UniqueConstraint('uid')
	)
	op.create_table('credentials',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('user_email', sa.Integer(), nullable=False),
	sa.Column('credential_id', sa.LargeBinary(), nullable=False),
	sa.Column('credential_public_key', sa.LargeBinary(), nullable=False),
	sa.Column('current_sign_count', sa.Integer(), nullable=True),
	sa.Column('credential_transport', sa.String(), nullable=True),
	sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
	sa.PrimaryKeyConstraint('id')
	)
	op.create_table('endusers',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('email', sa.String(), nullable=True),
	sa.Column('org', sa.Integer(), nullable=True),
	sa.ForeignKeyConstraint(['org'], ['users.id'], ),
	sa.PrimaryKeyConstraint('id')
	)
	op.create_table('endusercredentials',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('end_user_id', sa.Integer(), nullable=True),
	sa.Column('credential_id', sa.LargeBinary(), nullable=False),
	sa.Column('credential_public_key', sa.LargeBinary(), nullable=False),
	sa.Column('current_sign_count', sa.Integer(), nullable=True),
	sa.Column('credential_transport', sa.String(), nullable=True),
	sa.ForeignKeyConstraint(['end_user_id'], ['endusers.id'], ),
	sa.PrimaryKeyConstraint('id')
	)
	# ### end Alembic commands ###