"""end user cred has end user email link

Revision ID: e2c9dc6455c2
Revises: 8ec496d732dd
Create Date: 2023-06-07 16:59:16.100412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2c9dc6455c2'
down_revision = '8ec496d732dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
