"""Was not auto genrating

Revision ID: e33acf704ad1
Revises: a425df258c4f
Create Date: 2023-06-05 18:37:01.898916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e33acf704ad1'
down_revision = 'a425df258c4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('pricing_plan', sa.String(length=10), nullable=True))
    # op.add_column('users', sa.Column('login_count', sa.Integer(), nullable=True))
	pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'login_count')
    op.drop_column('users', 'pricing_plan')
    # ### end Alembic commands ###
