"""added api key to User model

Revision ID: e9c3e476a657
Revises: e33acf704ad1
Create Date: 2023-06-05 22:02:04.913648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9c3e476a657'
down_revision = 'e33acf704ad1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint("unique_api_key", ['api_key'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint("unique_api_key", type_='unique')

    # ### end Alembic commands ###
